### ISSUE TITLE
Can homebrew work yet?

### ISSUE THREAD

**Issue by ghost** [MoochMcGee/Emotionless#1]
It seems this project is super new but one of your latest commits mentions the Torus ELF binary almost running. That's 3D, no? Doesn't that require the GS to be emulated well? 

Do other homebrew work or the BIOS? This is unbelievable ... I've never seen a brand new PS2 emulator, barely around months already, nearly running homebrew and such. 

As for the TLB you mention on the .md, ZeroFrog, a programmer of PCSX2, wrote a small blog about it here: http://forums.pcsx2.net/Thread-blog-Virtual-Memory

**Comment by MoochMcGee** [comment]
Well, I'm not currently sure about the Torus demo anymore, but it does seem to be in a main loop. The BIOS currently does not work, and no homebrew works just yet. Just about all that's emulated at this point is an incomplete EE, an even more incomplete IOP, a basic DMAC, and the skeleton of the GIF.

Currently, I'm working on getting the original Budokai running. So far, it's running into lots of unimplemented syscalls. Also, with an unhacked ELF, be prepared for log files exceeding 1 GB before anything remotely interesting happens. Luckily, this is just RAM zeroing, so I hacked my ELF to skip it.

Of course, you're welcome to help with Emotionless. It could really use good programmers.

**Comment by mantlebreath** [comment]
So the goal of the emulator is to only focus on Budokai? I thought it's bad practice to try and tailor an emulator to just one game's implementation. I mean I can see if that's your first milestone, but I'm assuming that if you progressively keep the emulator up, many more games than just Budokai could work in the same state of the emulator's advancements (a lot of games, specifically simple ones like Budokai, don't need that perfect of emulation to work). If you haven't work on the GS, no proper video output will work. Honestly, the Emotion Engine's opcode interpreter and memory is probably the simplest thing to do, although the TLB can be a nightmare.

Also, when you get to the point of commercial games, I believe you'll need to work on mounting and reading sectors of the disk images, which is honestly not too hard from what I've seen in other PS2 emulator's code.

**Comment by MoochMcGee** [comment]
No, of course not! I eventually plan to run most if not all games somewhat decently.

**Comment by MoochMcGee** [comment]
And Budokai is nowhere NEAR a simple game, BTW.

**Comment by mantlebreath** [comment]
It may not be the simplest, but compared to a massive library of PS2 games, it's certainly closer to simple than difficult to emulate.

**Comment by Dokman** [comment]
FFX the most simple game

**Comment by Dokman** [comment]
did you will implement correctly the gpu mipmapping?

**Comment by MoochMcGee** [comment]
@Dokman I will certainly try to implement the GPU mipmapping. Also, please consider improving your English. Your poor English skills are quite the barrier to communication.

**Comment by Dokman** [comment]
yes sorry i have bad teachers TT
